name: Package lock diff.
description: Show package lock diff in comment
inputs:
  work-dir:
    description: 'Directory to run the diff in'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install lock diff
      shell: bash
      run: npm install -g lock-diff

    - name: Prepare package lock diff
      shell: bash
      run: |
        if [ ! -v github.event.inputs.work-dir ]; then
          git show ${{ github.event.pull_request.base.sha }}:package-lock.json > package-lock.old.json
          lock-diff package-lock.old.json package-lock.json --format=text >> package_diff.md || true
        else
          git show ${{ github.event.pull_request.base.sha }}:${{ inputs.work-dir }}/package-lock.json > package-lock.old.json
          lock-diff package-lock.old.json ${{ inputs.work-dir }}/package-lock.json --format=text >> package_diff.md || true
        fi

    - name: Add comment to PR
      shell: bash
      run: >
        if [[ -s package_diff.md ]]; then
          echo "### Package lock diff" > body.md
          echo "<pre>" >> body.md
          echo "$(cat package_diff.md)" >> body.md
          echo "</pre>" >> body.md
          jq -n --arg body "$(cat body.md)" '{body: $body}' > package_diff.json
          curl \
            -X POST \
            ${{ github.event.pull_request.comments_url }} \
            -H "Accept: application/vnd.github.v3.raw+json" \
            -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
            --data '@package_diff.json'
        fi
