name: Package lock diff.
description: Show package lock diff in comment
inputs:
  work-dir:
    description: 'Directory to run the diff in'
    required: false
    default: ''
  node_version:
    description: 'Node version to setup. Can set to blank string to disable node setup'
    required: false
    default: '20'
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      if: ${{ inputs.node_version != '' }}
      with:
        node-version: ${{ inputs.node_version }}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install lock diff
      shell: bash
      run: npm install -g https://github.com/stevelacey/lock-diff

    - name: Prepare package lock diff
      shell: bash
      run: |
        if [ -z "${{ inputs.work-dir }}" ]; then
          git show ${{ github.event.pull_request.base.sha }}:package-lock.json > package-lock.old.json
          lock-diff package-lock.old.json package-lock.json --format=text >> package_diff.md || true
        else
          git show ${{ github.event.pull_request.base.sha }}:${{ inputs.work-dir }}/package-lock.json > package-lock.old.json
          lock-diff package-lock.old.json ${{ inputs.work-dir }}/package-lock.json --format=text >> package_diff.md || true
        fi

    - name: Delete existing comment on PR
      shell: bash
      run: |
        existing_comment_id=$(curl -s \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
          ${{ github.event.pull_request.comments_url }} \
          | jq '.[] | select(.user.login=="github-actions[bot]") | select(.body|startswith("### Package lock diff")) | .id')

        if [ -n "$existing_comment_id" ]; then
          echo "Found existing comment with ID: $existing_comment_id. Deleting it."
          curl -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues/comments/$existing_comment_id
        else
          echo "No existing comment found."
        fi

    - name: Add comment to PR
      shell: bash
      run: |
        if [[ -s package_diff.md ]]; then
          echo "### Package lock diff" > body.md
          echo "<pre>" >> body.md
          echo "$(cat package_diff.md)" >> body.md
          echo "</pre>" >> body.md
          jq -n --arg body "$(cat body.md)" '{body: $body}' > package_diff.json
          curl \
            -X POST \
            ${{ github.event.pull_request.comments_url }} \
            -H "Accept: application/vnd.github.v3.raw+json" \
            -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
            --data '@package_diff.json'
        fi
