name: Composer lock diff.
description: Show composer lock diff in comment
inputs:
  work-dir:
    description: 'Directory to run the diff in'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Setup PHP with composer v2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer:v2
        coverage: none # Disable xDebug

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install composer lock diff
      shell: bash
      run: composer global require davidrjonas/composer-lock-diff:^1.7

    - name: Run composer lock diff
      shell: bash
      run: |
        if [ -z "${{ inputs.work-dir }}" ]; then
          ~/.composer/vendor/bin/composer-lock-diff --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --md >> composer_diff.md
        else
          ~/.composer/vendor/bin/composer-lock-diff --from ${{ github.event.pull_request.base.sha }}:${{ inputs.work-dir }}/composer.lock --to ${{ github.event.pull_request.head.sha }}:${{ inputs.work-dir }}/composer.lock --md >> composer_diff.md
        fi

    - name: Delete existing comment on PR
      shell: bash
      run: |
        existing_comment_id=$(curl -s \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
          ${{ github.event.pull_request.comments_url }} \
          | jq '.[] | select(.user.login=="github-actions[bot]") | select(.body|startswith("### Composer lock diff")) | .id')

        if [ -n "$existing_comment_id" ]; then
          echo "Found existing comment with ID: $existing_comment_id. Deleting it."
          curl -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues/comments/$existing_comment_id
        else
          echo "No existing comment found."
        fi

    - name: Add comment to PR
      shell: bash
      run: >
        if [[ -s composer_diff.md ]]; then
          echo "### Composer lock diff" > body.md
          echo "$(cat composer_diff.md)" >> body.md
          jq -n --arg body "$(cat body.md)" '{body: $body}' > composer_diff.json
          curl \
            -X POST \
            ${{ github.event.pull_request.comments_url }} \
            -H "Accept: application/vnd.github.v3.raw+json" \
            -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
            --data '@composer_diff.json'
        fi
